#ifndef SM_SHELLCORE_PROTOCOL_DEFS_H
#define SM_SHELLCORE_PROTOCOL_DEFS_H

/* Shared by C and the position-independent ShellCore bridge assembly. */
#define SM_SHELLCORE_SOCKET_PATH "/system_tmp/shadowmount.sock"
#define SM_SHELLCORE_PROTOCOL_MAGIC 0x534d5343
#define SM_SHELLCORE_PROTOCOL_VERSION 1
#define SM_SHELLCORE_REQUEST_LAUNCH_VALUE 1
#define SM_SHELLCORE_REQUEST_LAUNCH_FAILED_VALUE 2
#define SM_SHELLCORE_REQUEST_TITLE_ID_SIZE 32
#define SM_SHELLCORE_REQUEST_SIZE 40
#define SM_SHELLCORE_RESPONSE_SIZE 4
#define SM_SHELLCORE_BRIDGE_INSTALL_DIR_SIZE 1024

#endif
