#!/usr/bin/env python3
"""Generate the kstuff-lite SceShellCore capability table.

kstuff-lite carries its own per-firmware patch list, one header per firmware,
and each entry is an offset, the bytes written there and a comment naming the
patch.  Two of those patches are kstuff-lite's alone, so reading them back out
of the live SceShellCore is how a payload tells kstuff-lite from full kstuff.
The table is generated from those headers so a new firmware is picked up by
re-running this against a newer kstuff-lite rather than by transcription.

Only the retail arrays are read: the probe compares against retail offsets and
must miss on a devkit rather than match something unrelated.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

# The patch, and the substring of kstuff-lite's own comment that names it.
PATCHES = (
    ("sysdir", "getSceSysDirPath"),
    ("trophy", "trophies not unlocking"),
)
SIG_MAX = 6
ENTRY = re.compile(
    r'\{\s*(0[xX][0-9a-fA-F]+)\s*,\s*"((?:\\x[0-9a-fA-F]{2})+)"\s*,\s*(\d+)\s*\}'
    r"\s*,?[ \t]*(//[^\n]*)?"
)
RETAIL_ARRAY = re.compile(r"shellcore_patches_\d+_retail\s*\[\]\s*=\s*\{")


def retail_body(text: str) -> str:
    """The retail array's initialiser, brace-matched from its opening brace."""
    match = RETAIL_ARRAY.search(text)
    if not match:
        raise ValueError("no retail patch array")
    index, depth, out = match.end(), 1, []
    while depth:
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
        if depth:
            out.append(char)
        index += 1
    return "".join(out)


def read_header(path: Path) -> dict[str, tuple[int, bytes]]:
    found: dict[str, tuple[int, bytes]] = {}
    for entry in ENTRY.finditer(retail_body(path.read_text(encoding="utf-8"))):
        comment = entry.group(4) or ""
        for name, anchor in PATCHES:
            if anchor not in comment:
                continue
            if name in found:
                raise ValueError(f"{path.name}: two entries name {anchor!r}")
            data = bytes(
                int(byte, 16)
                for byte in re.findall(r"\\x([0-9a-fA-F]{2})", entry.group(2))
            )
            if len(data) != int(entry.group(3)):
                raise ValueError(f"{path.name}: {name} length disagrees with its bytes")
            if len(data) > SIG_MAX:
                raise ValueError(f"{path.name}: {name} is wider than the row holds")
            found[name] = (int(entry.group(1), 16), data)
    missing = [name for name, _ in PATCHES if name not in found]
    if missing:
        raise ValueError(f"{path.name}: no entry names {', '.join(missing)}")
    return found


def firmware_key(stem: str) -> int:
    major, minor = stem.split("_")
    return int(f"{int(major):02d}{minor}", 16)


def generate(root: Path) -> str:
    records = []
    for path in sorted(root.glob("*_*.h"), key=lambda p: firmware_key(p.stem)):
        major, minor = path.stem.split("_")
        patches = read_header(path)
        fields = [
            f"    .firmware = 0x{firmware_key(path.stem):04x}u,",
            f'    .name = "{int(major)}.{minor}",',
        ]
        for name, _ in PATCHES:
            offset, data = patches[name]
            signature = ", ".join(f"0x{byte:02x}" for byte in data)
            fields += [
                f"    .{name}_off = 0x{offset:x}u,",
                f"    .{name}_len = {len(data)}u,",
                f"    .{name}_sig = {{{signature}}},",
            ]
        records.append("  {\n" + "\n".join(fields) + "\n  }")
    if not records:
        raise ValueError(f"{root}: no kstuff-lite patch headers found")
    header = "/* Generated by tools/generate_kstuff_caps_offsets.py. */\n"
    return header + ",\n".join(records) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "root", type=Path, help="kstuff-lite ps5-kstuff/shellcore_patches directory"
    )
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = generate(args.root)
    if args.output:
        with args.output.open("w", encoding="utf-8", newline="\n") as file:
            file.write(output)
    else:
        print(output, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
